{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "passbolt-helm.fullname" . }}
  labels:
    {{- include "passbolt-helm.labels" . | nindent 4 }}
spec:
  {{ .Values.podDisruptionBudget.rule.type }}: {{.Values.podDisruptionBudget.rule.value}}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "passbolt-helm.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
